# Nome do workflow, aparece na "Actions"
name: Pipeline CI/CD
# Defini quando o pipeline será disparado
on: 
  push:
    branches:
      - main
  workflow_dispatch: # habilitar o botão "Run workflow" no Github Actions
jobs:
  #Primeiro job: build
  build:
    runs-on: ubuntu-latest # Imagem da maquina usada no CI
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Istalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Istalação das dependências
        run: npm install
      - name: Rodar o build
        run: npm run build
